/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author Muhammad Aqil Fahmi
 */
public class Calculator extends javax.swing.JFrame {

    String angka;
    double total, angka1, angka2, angka3;
    int pilih;
    public Calculator() {
        initComponents();
        angka="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonHapus = new javax.swing.JButton();
        jButtonPlusMinus = new javax.swing.JButton();
        jButtonModulo = new javax.swing.JButton();
        jButtonBagi = new javax.swing.JButton();
        jButtonAngka7 = new javax.swing.JButton();
        jButtonAngka8 = new javax.swing.JButton();
        jButtonAngka9 = new javax.swing.JButton();
        jButtonKali = new javax.swing.JButton();
        jButtonAngka4 = new javax.swing.JButton();
        jButtonAngka5 = new javax.swing.JButton();
        jButtonAngka6 = new javax.swing.JButton();
        jButtonKurang = new javax.swing.JButton();
        jButtonAngka1 = new javax.swing.JButton();
        jButtonAngka2 = new javax.swing.JButton();
        jButtonAngka3 = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jButtonKoma = new javax.swing.JButton();
        jButtonNol = new javax.swing.JButton();
        jButtonSamaDengan = new javax.swing.JButton();
        display = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonHapus.setText("C");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        jButtonPlusMinus.setText("-/+");
        jButtonPlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusMinusActionPerformed(evt);
            }
        });

        jButtonModulo.setText("%");
        jButtonModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModuloActionPerformed(evt);
            }
        });

        jButtonBagi.setText("/");
        jButtonBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBagiActionPerformed(evt);
            }
        });

        jButtonAngka7.setText("7");
        jButtonAngka7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAngka7ActionPerformed(evt);
            }
        });

        jButtonAngka8.setText("8");
        jButtonAngka8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAngka8ActionPerformed(evt);
            }
        });

        jButtonAngka9.setText("9");
        jButtonAngka9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAngka9ActionPerformed(evt);
            }
        });

        jButtonKali.setText("x");
        jButtonKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKaliActionPerformed(evt);
            }
        });

        jButtonAngka4.setText("4");
        jButtonAngka4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAngka4ActionPerformed(evt);
            }
        });

        jButtonAngka5.setText("5");
        jButtonAngka5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAngka5ActionPerformed(evt);
            }
        });

        jButtonAngka6.setText("6");
        jButtonAngka6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAngka6ActionPerformed(evt);
            }
        });

        jButtonKurang.setText("-");
        jButtonKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKurangActionPerformed(evt);
            }
        });

        jButtonAngka1.setText("1");
        jButtonAngka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAngka1ActionPerformed(evt);
            }
        });

        jButtonAngka2.setText("2");
        jButtonAngka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAngka2ActionPerformed(evt);
            }
        });

        jButtonAngka3.setText("3");
        jButtonAngka3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAngka3ActionPerformed(evt);
            }
        });

        jButtonPlus.setText("+");
        jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusActionPerformed(evt);
            }
        });

        jButtonKoma.setText(",");
        jButtonKoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKomaActionPerformed(evt);
            }
        });

        jButtonNol.setText("0");
        jButtonNol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNolActionPerformed(evt);
            }
        });

        jButtonSamaDengan.setText("=");
        jButtonSamaDengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSamaDenganActionPerformed(evt);
            }
        });

        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBagi, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAngka7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAngka8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAngka4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAngka5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAngka1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAngka2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonKoma, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonNol, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAngka3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonAngka9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonAngka6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonKali, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jButtonSamaDengan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(display))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(display, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonHapus)
                        .addComponent(jButtonPlusMinus)
                        .addComponent(jButtonModulo))
                    .addComponent(jButtonBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAngka7)
                    .addComponent(jButtonAngka8)
                    .addComponent(jButtonAngka9)
                    .addComponent(jButtonKali))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAngka6)
                    .addComponent(jButtonKurang)
                    .addComponent(jButtonAngka5)
                    .addComponent(jButtonAngka4))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAngka2)
                    .addComponent(jButtonAngka1)
                    .addComponent(jButtonAngka3)
                    .addComponent(jButtonPlus))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonKoma)
                    .addComponent(jButtonNol)
                    .addComponent(jButtonSamaDengan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        display.setText("");
        angka1=0;
        angka2=0;
        angka3=0;
        total=0;
        angka="";
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonPlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusMinusActionPerformed
        angka2=Double.parseDouble(angka);
        total=0-angka2;
        angka=Double.toString(total);
        display.setText(angka);
        
    }//GEN-LAST:event_jButtonPlusMinusActionPerformed

    private void jButtonModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModuloActionPerformed
        angka2=Double.parseDouble(angka);
        total=angka2/100;
        angka=Double.toString(total);
        display.setText(angka);
    }//GEN-LAST:event_jButtonModuloActionPerformed

    private void jButtonBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBagiActionPerformed
       angka1=Double.parseDouble(angka);
       display.setText("/");
       angka="";
       pilih=4;
    }//GEN-LAST:event_jButtonBagiActionPerformed

    private void jButtonAngka7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAngka7ActionPerformed
        angka+="7";
        display.setText(angka);
    }//GEN-LAST:event_jButtonAngka7ActionPerformed

    private void jButtonAngka8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAngka8ActionPerformed
        angka+="8";
        display.setText(angka);
    }//GEN-LAST:event_jButtonAngka8ActionPerformed

    private void jButtonAngka9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAngka9ActionPerformed
        angka+=9;
        display.setText(angka);
    }//GEN-LAST:event_jButtonAngka9ActionPerformed

    private void jButtonKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKaliActionPerformed
        angka1=Double.parseDouble(angka);
        display.setText("x");
        angka="";
        pilih=3;
    }//GEN-LAST:event_jButtonKaliActionPerformed

    private void jButtonAngka4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAngka4ActionPerformed
        angka+="4";
        display.setText(angka);
    }//GEN-LAST:event_jButtonAngka4ActionPerformed

    private void jButtonAngka5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAngka5ActionPerformed
        angka+="5";
        display.setText(angka);
    }//GEN-LAST:event_jButtonAngka5ActionPerformed

    private void jButtonAngka6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAngka6ActionPerformed
        angka+="6";
        display.setText(angka);
    }//GEN-LAST:event_jButtonAngka6ActionPerformed

    private void jButtonKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKurangActionPerformed
        angka1=Double.parseDouble(angka);
        display.setText("-");
        angka="";
        pilih=2;
        
        
    }//GEN-LAST:event_jButtonKurangActionPerformed

    private void jButtonAngka1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAngka1ActionPerformed
        angka+="1";
        display.setText(angka);
    }//GEN-LAST:event_jButtonAngka1ActionPerformed

    private void jButtonAngka2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAngka2ActionPerformed
       angka+="2";
        display.setText(angka);
    }//GEN-LAST:event_jButtonAngka2ActionPerformed

    private void jButtonAngka3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAngka3ActionPerformed
        angka+="3";
        display.setText(angka);
    }//GEN-LAST:event_jButtonAngka3ActionPerformed

    private void jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusActionPerformed
       angka1=Double.parseDouble(angka);
       display.setText("+");
       angka="";
       pilih=1;
    }//GEN-LAST:event_jButtonPlusActionPerformed

    private void jButtonKomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKomaActionPerformed
        angka+=",";
        display.setText(angka);
    }//GEN-LAST:event_jButtonKomaActionPerformed

    private void jButtonNolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNolActionPerformed
       angka+="0";
       display.setText(angka);
       
    }//GEN-LAST:event_jButtonNolActionPerformed

    private void jButtonSamaDenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSamaDenganActionPerformed
        switch(pilih)
        {
            case 1 -> 
            { angka2=Double.parseDouble(angka);
              total=angka1+angka2;
               angka = Integer.toString((int) total);
              display.setText(angka);
                
            }
            
            case 2 -> 
            { angka2=Double.parseDouble(angka);
              total=angka1-angka2;
              angka = Integer.toString((int) total);
              display.setText(angka);
                
            }
            
            case 3 -> 
            { angka2=Double.parseDouble(angka);
              total=angka1*angka2;
              angka = Integer.toString((int) total);
              display.setText(angka);
    
            }
            
            case 4 -> 
            { angka2=Double.parseDouble(angka);
              total=angka1/angka2;
             angka = Integer.toString((int) total);
              display.setText(angka);
              
            }
            
            case 5 -> 
            { angka2=Double.parseDouble(angka);
              total=angka2%angka1;
              angka = Integer.toString((int) total);
              display.setText(angka);
                
            }
        }
    }//GEN-LAST:event_jButtonSamaDenganActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        
    }//GEN-LAST:event_displayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Calculator().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField display;
    private javax.swing.JButton jButtonAngka1;
    private javax.swing.JButton jButtonAngka2;
    private javax.swing.JButton jButtonAngka3;
    private javax.swing.JButton jButtonAngka4;
    private javax.swing.JButton jButtonAngka5;
    private javax.swing.JButton jButtonAngka6;
    private javax.swing.JButton jButtonAngka7;
    private javax.swing.JButton jButtonAngka8;
    private javax.swing.JButton jButtonAngka9;
    private javax.swing.JButton jButtonBagi;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonKali;
    private javax.swing.JButton jButtonKoma;
    private javax.swing.JButton jButtonKurang;
    private javax.swing.JButton jButtonModulo;
    private javax.swing.JButton jButtonNol;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JButton jButtonPlusMinus;
    private javax.swing.JButton jButtonSamaDengan;
    // End of variables declaration//GEN-END:variables

}